using Content.Client.Cargo.Systems;
using Content.Client.Cargo.UI;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Cargo;
using Content.Shared.Cargo.Components;
using Content.Shared.Cargo.Prototypes;
using Content.Shared.CrewAccesses.Components;
using Content.Shared.CrewAssignments.Components;
using Content.Shared.CrewAssignments.Prototypes;
using Content.Shared.Radio;
using Content.Shared.Station.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Linq;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.CrewAssignments.UI
{

    [GenerateTypedNameReferences]
    public sealed partial class StationModificationMenu : FancyWindow
    {
        private readonly IPrototypeManager _protoManager;
        private readonly CargoSystem _cargoSystem;
        private readonly SpriteSystem _spriteSystem;
        private EntityUid _owner;
        private EntityUid? _station;
        private int? _lastAssignmentSelected;
        private int? _lastChannelSelected;
        private readonly List<ProtoId<RadioChannelPrototype>> _channelOrder = new();
        private bool _suppressColorCallbacks;
        public string? LastAssignmentCreated;
        Dictionary<string, CrewAccess>? _accesses;
        Dictionary<int, CrewAssignment>? _assignments;
        public Dictionary<ProtoId<RadioChannelPrototype>, FactionRadioData>? RadioData;


        public event Action<ButtonEventArgs>? OnOwnerPressed;
        public event Action<ButtonToggledEventArgs>? OnAssignmentAccessPressed;
        public event Action<ButtonToggledEventArgs>? OnChannelAccessPressed;

        public StationModificationMenu(EntityUid owner, IEntityManager entMan, IPrototypeManager protoManager, SpriteSystem spriteSystem)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _protoManager = protoManager;
            _cargoSystem = entMan.System<CargoSystem>();
            _spriteSystem = spriteSystem;
            _owner = owner;

            Title = entMan.GetComponent<MetaDataComponent>(owner).EntityName;
            TabContainer.SetTabTitle(0, "General");
            TabContainer.SetTabTitle(1, "Assignments");
            TabContainer.SetTabTitle(2, "Radio");
            TabContainer.SetTabTitle(3, "Upgrade");
            PossibleAccesses.OnItemSelected += OnDelAccessSelected;
            PossibleAssignments.OnItemSelected += OnAssignmentSelected;
            PossibleChannels.OnItemSelected += OnChannelSelected;
            CustomChannelHotkey.IsValid = text => text.Length <= 1;
            EditChannelHotkey.IsValid = text => text.Length <= 1;
            ChannelColorPicker.OnColorChanged += OnChannelColorChanged;

            _suppressColorCallbacks = true;
            ChannelColorPicker.Color = Color.FromSrgb(new Color(44, 219, 44));
            _suppressColorCallbacks = false;
            UpdateColorPreview(ChannelColorPreview, ChannelColorPicker.Color);

            FactionTagField.OnTextChanged += _ =>
            {
                if (FactionTagField.Text.Length <= 4)
                    return;

                FactionTagField.Text = FactionTagField.Text[..4];
                FactionTagField.CursorPosition = FactionTagField.Text.Length;
            };

        }

        private static Color ClampCustomChannelColor(Color color)
        {
            // Persistence 14: Mirror the server-side HSV value clamp in the client preview so the editor shows the exact brightness range that Save will preserve.
            var hsv = Color.ToHsv(color);
            if (hsv.Z < 2f / 3f)
                hsv.Z = 2f / 3f;

            return Color.FromHsv(hsv);
            // End Persistence 14
        }

        private void OnChannelColorChanged(Color color)
        {
            if (_suppressColorCallbacks)
                return;

            var clamped = ClampCustomChannelColor(color);
            if (clamped != color)
            {
                _suppressColorCallbacks = true;
                ChannelColorPicker.Color = clamped;
                _suppressColorCallbacks = false;
                color = clamped;
            }

            UpdateColorPreview(ChannelColorPreview, color);
        }

        private void UpdateColorPreview(PanelContainer panel, Color color)
        {
            if (_suppressColorCallbacks)
                return;

            panel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = color,
                BorderColor = new Color(128, 128, 128),
                BorderThickness = new Thickness(1),
            };
        }

        private void OnChannelSelected(OptionButton.ItemSelectedEventArgs args)
        {
            _lastChannelSelected = args.Id;
            PossibleChannels.SelectId(args.Id);
            UpdateChannel();

        }
        private void OnDelAccessSelected(OptionButton.ItemSelectedEventArgs args)
        {
            PossibleAccesses.SelectId(args.Id);

        }
        private void OnAssignmentSelected(OptionButton.ItemSelectedEventArgs args)
        {
            _lastAssignmentSelected = args.Id;
            PossibleAssignments.SelectId(args.Id);
            UpdateAssignment();

        }
        public void UpdateStation(EntityUid station, string name, string factionTag)
        {

            _station = station;
            StationNameLabel.Text = name;
            StationNameField.Text = name;
            FactionTagField.Text = factionTag;
        }
        public void UpdateOwners(List<string> owners)
        {
            Requests.RemoveAllChildren();
            foreach (var owner in owners)
            {
                var button = new StationOwnerButton(owner);
                button.OnPressed += (args) => { OnOwnerPressed?.Invoke(args); };
                Requests.AddChild(button);
            }
        }

        public void UpdateChannels(Dictionary<ProtoId<RadioChannelPrototype>, FactionRadioData> radioData)
        {
            RadioData = radioData;
            PossibleChannels.Clear();
            _channelOrder.Clear();
            foreach (var owner in radioData)
            {
                if (!owner.Value.IsCustom)
                    continue;

                _protoManager.Resolve(owner.Key, out var radioProto);
                if (radioProto == null) continue;

                var display = owner.Value.IsCustom && !string.IsNullOrWhiteSpace(owner.Value.CustomName)
                    ? owner.Value.CustomName!
                    : radioProto.LocalizedName;

                if (owner.Value.IsCustom && owner.Value.Hotkey != '\0')
                    display = $"{display} (:{owner.Value.Hotkey})";

                _channelOrder.Add(owner.Key);
                PossibleChannels.AddItem(display, _channelOrder.Count - 1);
            }

            if (_channelOrder.Count == 0)
            {
                _lastChannelSelected = null;
            }
            else if (_lastChannelSelected != null)
            {
                PossibleChannels.TrySelectId(_lastChannelSelected.Value);
            }
            else
            {
                PossibleChannels.SelectId(0);
                _lastChannelSelected = 0;
            }
            UpdateChannel();
        }

        public ProtoId<RadioChannelPrototype>? SelectedChannelId
        {
            get
            {
                var id = PossibleChannels.SelectedId;
                if (id < 0 || id >= _channelOrder.Count)
                    return null;

                return _channelOrder[id];
            }
        }

        public void UpdateChannel()
        {
            if (RadioData == null)
                return;

            var selectedId = SelectedChannelId;
            if (selectedId == null || !RadioData.TryGetValue(selectedId.Value, out var data))
            {
                ChannelEnable.Pressed = false;
                ChannelDisable.Pressed = false;
                ChannelEnable.Disabled = true;
                ChannelDisable.Disabled = true;
                EditChannelName.Text = string.Empty;
                EditChannelHotkey.Text = string.Empty;
                EditChannelButton.Disabled = true;
                EditChannelHint.Text = "No custom channels available to edit.";

                foreach (Button button in ChannelAccessesBC.Children)
                {
                    button.Pressed = false;
                }

                return;
            }

            ChannelEnable.Disabled = false;
            ChannelDisable.Disabled = false;

            ChannelEnable.Pressed = data.Enabled;
            ChannelDisable.Pressed = !data.Enabled;

            _suppressColorCallbacks = true;
            if (data.IsCustom)
            {
                EditChannelName.Text = data.CustomName ?? string.Empty;
                EditChannelHotkey.Text = data.Hotkey == '\0' ? string.Empty : data.Hotkey.ToString();
                ChannelColorPicker.Color = ClampCustomChannelColor(data.GetColor());
                EditChannelButton.Disabled = false;
                EditChannelHint.Text = string.Empty;
            }
            else
            {
                _protoManager.Resolve(selectedId.Value, out var radioProto);
                EditChannelName.Text = radioProto?.LocalizedName ?? selectedId.Value;
                EditChannelHotkey.Text = radioProto == null || radioProto.KeyCode == '\0' ? string.Empty : radioProto.KeyCode.ToString();
                ChannelColorPicker.Color = radioProto?.Color ?? Color.FromSrgb(new Color(44, 219, 44));
                EditChannelButton.Disabled = true;
                EditChannelHint.Text = "Only custom channels can be edited.";
            }
            _suppressColorCallbacks = false;
            UpdateColorPreview(ChannelColorPreview, ChannelColorPicker.Color);

            foreach (Button button in ChannelAccessesBC.Children)
            {
                if (button.Text == null) continue;
                if (data.Access.Contains(button.Text))
                {
                    button.Pressed = true;
                }
                else
                {
                    button.Pressed = false;
                }
            }
        }


        public void UpdateAccesses(Dictionary<string, CrewAccess> accesses)
        {
            _accesses = accesses;
            AssignmentAccessesBC.RemoveAllChildren();
            ChannelAccessesBC.RemoveAllChildren();
            PossibleAccesses.Clear();
            foreach (var owner in accesses)
            {
                var button = new AssignmentAccessButton(owner.Key);
                button.ToggleMode = true;
                button.OnToggled += (args) => { OnAssignmentAccessPressed?.Invoke(args); };
                button.VerticalExpand = false;
                button.HorizontalExpand = false;
                AssignmentAccessesBC.AddChild(button);
                Button button2 = new Button();
                button2.Text = owner.Key;
                button2.ToggleMode = true;
                button2.OnToggled += (args) => { OnChannelAccessPressed?.Invoke(args); };
                button2.VerticalExpand = false;
                button2.HorizontalExpand = false;
                ChannelAccessesBC.AddChild(button2);
                PossibleAccesses.AddItem(owner.Key);
            }

        }

        public void UpdateUpgrades(ProtoId<FactionLevelPrototype> level, int balance)
        {
            _protoManager.Resolve(level, out var levelProto);
            if (levelProto == null) return;
            FactionLevelPrototype? nextLevelProto = null;

            if (levelProto.Next != null)
                _protoManager.Resolve(levelProto.Next, out nextLevelProto);

            CurrentFactionLevelLabel.Text = levelProto.Name;
            string levelDesc = $"Owned Tile Limit:[color=yellow]{levelProto.TileLimit}[/color]";
            if (levelProto.TradestationClaim)
                levelDesc += $"\n[color=green]Can claim trade stations[/color]";
            CurrentBenefitsLabel.SetMarkup(levelDesc);
            string nextLevelDesc;
            if (nextLevelProto == null)
            {
                NextFactionLevelLabel.Text = "Max Level Attained";
                nextLevelDesc = "[color=green]Maximum Level Attained[/color]";
                LevelPurchaseButton.Visible = false;
            }
            else
            {
                NextFactionLevelLabel.Text = nextLevelProto.Name;
                nextLevelDesc = $"Owned Tile Limit:[color=green]{nextLevelProto.TileLimit}[/color]";
                if (nextLevelProto.TradestationClaim)
                {
                    nextLevelDesc += $"\n[color=green]Can claim trade stations[/color]";
                }
                LevelPurchaseButton.Visible = true;
                LevelPurchaseButton.Text = $"${nextLevelProto.Cost}";
            }
            NextBenefitsLabel.SetMarkup(nextLevelDesc);
            AccountBalanceLabel.Text = $"${balance}";

        }

        public void UpdateAssignments(Dictionary<int, CrewAssignment> assignments)
        {
            _assignments = assignments;
            PossibleAssignments.Clear();
            foreach (var owner in assignments)
            {
                PossibleAssignments.AddItem(owner.Value.Name, owner.Key);
                if (LastAssignmentCreated == owner.Value.Name) _lastAssignmentSelected = owner.Key;
            }
            if (_lastAssignmentSelected != null)
            {
                PossibleAssignments.TrySelectId(_lastAssignmentSelected.Value);
            }
            UpdateAssignment();
        }
        public void UpdateAssignment()
        {
            int id = PossibleAssignments.SelectedId;
            if (_assignments == null) return;
            if (_assignments.TryGetValue(id, out var assignment))
            {
                AssignmentDetails.Visible = true;
                AssignmentNameField.Text = assignment.Name;
                WageSpinBox.Value = assignment.Wage;
                CLevelSpinBox.Value = assignment.Clevel;
                SpendingLimitSpinBox.Value = assignment.SpendingLimit;

                if (assignment.CanClaim)
                {
                    ClaimBtn.Pressed = true;
                }
                else
                {
                    ClaimBtn.Pressed = false;
                }
                if (assignment.CanAssign)
                {
                    ReassignmentBtn.Pressed = true;
                }
                else
                {
                    ReassignmentBtn.Pressed = false;
                }
                if (assignment.CanEditGeneralRecord)
                {
                    GenRecBtn.Pressed = true;
                }
                else
                {
                    GenRecBtn.Pressed = false;
                }
                foreach (Button button in AssignmentAccessesBC.Children)
                {
                    if (button.Text == null) continue;
                    if (assignment.AccessIDs.Contains(button.Text))
                    {
                        button.Pressed = true;
                    }
                    else
                    {
                        button.Pressed = false;
                    }
                }
            }
            else
            {
                AssignmentDetails.Visible = false;
                AssignmentNameField.Text = "";
                WageSpinBox.Value = 0;
                CLevelSpinBox.Value = 0;
                foreach (Button button in AssignmentAccessesBC.Children)
                {
                    button.Pressed = false;
                }
            }
        }
    }
}

public sealed partial class AssignmentAccessButton : Button
{
    public string Owner { get; set; } = "";

    public AssignmentAccessButton(string owner)
    {
        Owner = owner;
        Text = owner;
    }
}
