using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Persistence14.Research.RecipeRelay;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Persistence14.Research.RecipeRelay;

[GenerateTypedNameReferences]
public sealed partial class RecipeRelaySourceWindow : FancyWindow
{
    public Action<NetEntity>? OnClientPressed;

    public RecipeRelaySourceWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(RecipeRelaySourceBoundUserInterfaceState state)
    {
        ClientList.RemoveAllChildren();

        foreach (var receiver in state.Receivers)
        {
            ClientList.AddChild(ConstructReceiverEntry(receiver));
        }
    }

    private Control ConstructReceiverEntry(RecipeRelayReceiverState state)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 8,
            Margin = new Thickness(4)
        };

        container.AddChild(new Label
        {
            Text = state.Name,
            HorizontalExpand = true
        });

        if (state.Connected)
        {
            container.AddChild(new Label
            {
                Text = "[Linked]",
                HorizontalAlignment = HAlignment.Right
            });
        }

        var button = new Button
        {
            HorizontalAlignment = HAlignment.Right,
            ToggleMode = true,
            Pressed = state.Connected,
            Disabled = !state.CanChangeState,
            Margin = new Thickness(2, 1),
            MinSize = new Vector2(60, 0),
            Text = $"{(state.Connected ? "Unlink" : "Link")}"
        };


#pragma warning disable CS0618 // Type or member is obsolete
        if (state.BlockedTooltip is not null && Loc.TryGetString(state.BlockedTooltip, out var loc))
            button.ToolTip = loc;
        else
            button.ToolTip = state.BlockedTooltip;
#pragma warning restore CS0618

        button.OnPressed += _ =>
        {
            OnClientPressed?.Invoke(state.Entity);
        };

        container.AddChild(button);

        return container;
    }
}