using Content.Client.CrewAssignments.UI;
using Content.Client.Message;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.CCVar;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;
using static Content.Shared.Access.Components.IdCardConsoleComponent;

namespace Content.Client.Access.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class IdCardConsoleWindow : DefaultWindow
    {
        [Dependency] private readonly IConfigurationManager _cfgManager = default!;

        private readonly IdCardConsoleBoundUserInterface _owner;


        private string? _lastFullName;


        public IdCardConsoleWindow(IdCardConsoleBoundUserInterface owner, IPrototypeManager prototypeManager,
            List<ProtoId<AccessLevelPrototype>> accessLevels)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _owner = owner;

            FullNameLineEdit.OnTextEntered += _ => SubmitData();
            FullNameLineEdit.IsValid = s => s.Length <= _cfgManager.GetCVar(CCVars.MaxNameLength);
            FullNameLineEdit.OnTextChanged += _ =>
            {
                FullNameSaveButton.Disabled = FullNameSaveButton.Text == _lastFullName;
            };
            FullNameSaveButton.OnPressed += _ => SubmitData();
            SpendingReset.OnPressed += _ => ResetSpending();

            SaveGeneralRecordBtn.OnPressed += _ => SaveGeneralRecord();
            PrintGeneralRecordBtn.OnPressed += _ => PrintGeneralRecord();

            SaveCriminalRecordBtn.OnPressed += _ => SaveCriminalRecord();
            PrintCriminalRecordBtn.OnPressed += _ => PrintCriminalRecord();

            SaveMedicalRecordBtn.OnPressed += _ => SaveMedicalRecord();
            PrintMedicalRecordBtn.OnPressed += _ => PrintMedicalRecord();

            MainTabs.SetTabTitle(0, "Assignment");
            MainTabs.SetTabTitle(1, "General Record");
            MainTabs.SetTabTitle(2, "Criminal Record");
            MainTabs.SetTabTitle(3, "Medical Record");

            GeneralTabs.SetTabTitle(0, "View");
            GeneralTabs.SetTabTitle(1, "Edit");

            CriminalTabs.SetTabTitle(0, "View");
            CriminalTabs.SetTabTitle(1, "Edit");

            MedicalTabs.SetTabTitle(0, "View");
            MedicalTabs.SetTabTitle(1, "Edit");


        }

        public void SearchRecord(string fullName)
        {
            ModeTabs.CurrentTab = 0;
            _owner.SearchRecord(fullName);
        }
        public void UpdateState(IdCardConsoleBoundUserInterfaceState state)
        {
            ListView.RemoveAllChildren();
            ModeTabs.SetTabTitle(0, "Record View");
            ModeTabs.SetTabTitle(1, "List View");
            foreach (var record in state.AllRecords)
            {
                BoxContainer container = new();
                container.Orientation = BoxContainer.LayoutOrientation.Horizontal;
                Label label = new();
                label.Text = record.LastPaid.ToString();
                Button button = new();
                String assignmentName = "Unassigned";
                if (state.AllAssignments != null && state.AllAssignments.ContainsKey(record.AssignmentID))
                {
                    var assignment = state.AllAssignments[record.AssignmentID];
                    assignmentName = assignment.Name;
                }
                button.Text = $"{record.Name} [{assignmentName}]";
                button.OnPressed += _ => { SearchRecord(record.Name); };
                container.AddChild(button);
                Control control = new();
                control.HorizontalExpand = true;
                container.AddChild(control);
                container.AddChild(label);
                ListView.AddChild(container);
            }
            PrivilegedIdButton.Text = state.IsPrivilegedIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            PrivilegedIdLabel.Text = state.PrivilegedIdName;

            TargetIdButton.Text = state.IsTargetIdPresent
                ? Loc.GetString("id-card-console-window-eject-button")
                : Loc.GetString("id-card-console-window-insert-button");

            TargetIdLabel.Text = state.TargetIdName;

            var interfaceEnabled =
                state.IsPrivilegedIdPresent && state.IsPrivilegedIdAuthorized && state.TargetIdFullName != null && state.TargetIdFullName != "";
            if (state.TargetIdFullName != null && state.TargetIdFullName != "")
            {
                FullNameLineEdit.Text = state.TargetIdFullName;
                SelectedAccountLabel.Text = state.TargetIdFullName;
                AccountDetails.Visible = true;
            }
            else
            {
                SelectedAccountLabel.Text = "*None*";
                AccountDetails.Visible = false;
            }

            var fullNameDirty = _lastFullName != null && FullNameLineEdit.Text != state.TargetIdFullName;

            FullNameLabel.Modulate = interfaceEnabled ? Color.White : Color.Gray;
            if (!fullNameDirty)
            {
                FullNameLineEdit.Text = state.TargetIdFullName ?? string.Empty;
            }

            FullNameSaveButton.Disabled = !fullNameDirty;

            if (state.Assignment != null)
            {
                AssignmentLabel.Text = state.Assignment.Name;
                SpendingLabel.Text = $"${state.SpentFunds}/{state.Assignment.SpendingLimit}";
            }
            else
            {
                AssignmentLabel.Text = "*Unassigned*";
                SpendingLabel.Text = $"${state.SpentFunds}/0";
            }
            _lastFullName = state.TargetIdFullName;
            AccessLevelControlContainer.RemoveAllChildren();
            if (state.AllAssignments != null)
            {

                foreach (var item in state.AllAssignments)
                {
                    var id = item.Key;
                    var assignment = item.Value;
                    var button = new AssignmentButton(id, assignment.Name);
                    button.OnPressed += (args) => { _owner.OnAssignmentPressed(args); };
                    AccessLevelControlContainer.AddChild(button);
                    if (state.CrewRecord == null || (!state.IsOwner && state.PrivAssignment == null))
                    {
                        button.Disabled = true;
                    }
                    else
                    {

                        if (state.Assignment != null && state.Assignment.ID == id)
                        {
                            button.Pressed = true;
                        }
                        else if (!state.IsOwner && ((state.PrivAssignment == null) || assignment.Clevel >= state.PrivAssignment.Clevel || (state.Assignment != null && state.Assignment.Clevel >= state.PrivAssignment.Clevel)))
                        {
                            button.Disabled = true;
                        }
                    }
                }

            }
            if (state.CrewRecord != null)
            {
                GeneralRecordLabel.SetMarkup(state.CrewRecord.GeneralRecord);
                GeneralRecordTE.TextRope = new Rope.Leaf(state.CrewRecord.GeneralRecord);

                MedicalRecordLabel.SetMarkup(state.CrewRecord.MedicalRecord);
                MedicalRecordTE.TextRope = new Rope.Leaf(state.CrewRecord.MedicalRecord);

                CriminalRecordLabel.SetMarkup(state.CrewRecord.CriminalRecord);
                CriminalRecordTE.TextRope = new Rope.Leaf(state.CrewRecord.CriminalRecord);
            }
            if (!state.IsOwner && state.PrivAssignment != null)
            {
                if (state.IsOwner || state.PrivAssignment.CanEditGeneralRecord)
                {
                    EditGeneralRecord.Visible = true;
                }
                else
                {
                    EditGeneralRecord.Visible = false;
                    EditCriminalRecord.Visible = false;
                    EditMedicalRecord.Visible = false;
                }
            }
            else
            {
                EditGeneralRecord.Visible = false;
                EditMedicalRecord.Visible = false;
            }
        }


        private void PrintGeneralRecord()
        {
            _owner.PrintGeneralRecord();
            Close();
        }
        private void SaveGeneralRecord()
        {
            _owner.SaveGeneralRecord(Rope.Collapse(GeneralRecordTE.TextRope));
        }

        private void PrintCriminalRecord()
        {
            _owner.PrintCriminalRecord();
            Close();
        }
        private void SaveCriminalRecord()
        {
            _owner.SaveCriminalRecord(Rope.Collapse(CriminalRecordTE.TextRope));
        }

        private void PrintMedicalRecord()
        {
            _owner.PrintMedicalRecord();
            Close();
        }
        private void SaveMedicalRecord()
        {
            _owner.SaveMedicalRecord(Rope.Collapse(MedicalRecordTE.TextRope));
        }

        private void ResetSpending()
        {
            _owner.ResetSpending();
        }
        private void SubmitData()
        {
            _owner.SearchRecord(FullNameLineEdit.Text);
        }
    }
}
