using Content.Client.Radio.Ui;
using Content.Shared.Access;
using Content.Shared.Access.Systems;
using Content.Shared.GridControl.Components;
using Content.Shared.Radio.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System;

namespace Content.Client.Radio.Ui;

[GenerateTypedNameReferences]
public sealed partial class HeadsetMenuWindow : DefaultWindow
{
    public HeadsetMenuBoundUserInterface? BUI;
    private bool _updating;

    public HeadsetMenuWindow()
    {
        RobustXamlLoader.Load(this);
        AllInputs.OnToggled += OnAllInputsToggled;
        AllOutputs.OnToggled += OnAllOutputsToggled;
    }

    private void OnAllInputsToggled(BaseButton.ButtonToggledEventArgs args)
    {
        if (_updating || BUI == null)
            return;

        BUI.SendMessage(new HeadsetMenuInputToggle(0, args.Pressed));
    }

    private void OnAllOutputsToggled(BaseButton.ButtonToggledEventArgs args)
    {
        if (_updating || BUI == null)
            return;

        BUI.SendMessage(new HeadsetMenuOutputToggle(0, args.Pressed));
    }

    public void UpdateState(IPrototypeManager protoManager, HeadsetMenuBoundUserInterfaceState state)
    {
        _updating = true;
        PossibleInputs.RemoveAllChildren();
        PossibleOutputs.RemoveAllChildren();

        var receiveAll = state.RecieveFrom.Count == 0;
        var transmitAll = state.TransmitTo.Count == 0;
        AllInputs.Pressed = receiveAll;
        AllOutputs.Pressed = transmitAll;

        foreach (var kv in state.FormattedStations)
        {
            var inputToggle = new CheckBox
            {
                Text = kv.Value,
                Pressed = !receiveAll && state.RecieveFrom.Contains(kv.Key),
                Disabled = receiveAll,
            };
            var outputToggle = new CheckBox
            {
                Text = kv.Value,
                Pressed = !transmitAll && state.TransmitTo.Contains(kv.Key),
                Disabled = transmitAll,
            };

            var stationId = kv.Key;
            inputToggle.OnToggled += args =>
            {
                if (_updating || BUI == null)
                    return;

                BUI.SendMessage(new HeadsetMenuInputToggle(stationId, args.Pressed));
            };

            outputToggle.OnToggled += args =>
            {
                if (_updating || BUI == null)
                    return;

                BUI.SendMessage(new HeadsetMenuOutputToggle(stationId, args.Pressed));
            };

            PossibleInputs.AddChild(inputToggle);
            PossibleOutputs.AddChild(outputToggle);
        }

        _updating = false;

    }

}
