using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._Persistence14.Research.Anomalies;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Persistence14.Anomaly;

[GenerateTypedNameReferences]
public sealed partial class AnomalyInfoCard : PanelContainer
{
    public AnomalyInfoCard()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetChances(float environmental, float infectious)
    {
        EnvironmentalChance.Text = $"{environmental:P0}";
        InfectiousChance.Text = $"{infectious:P0}";
    }

    public void SetAnomaly(AnomalyPrototype anomaly, float probability, bool forcedEnvironmental, bool forcedInfectious)
    {
        var environmental = 0f;
        var infectious = 0f;

        if (anomaly.HasEnvironmental && anomaly.HasInfectious && !forcedEnvironmental && !forcedInfectious)
        {
            var total = anomaly.EnvironmentalWeight + anomaly.InfectiousWeight;
            environmental = probability * anomaly.EnvironmentalWeight / total;
            infectious = probability * anomaly.InfectiousWeight / total;
        }
        else if (anomaly.HasEnvironmental)
            environmental = probability;
        else if (anomaly.HasInfectious)
            infectious = probability;

        if (forcedEnvironmental) infectious = 0f;
        if (forcedInfectious) environmental = 0f;

        SetChances(environmental, infectious);

        AnomalyImage.SetPrototype(anomaly.ImageEntity);
        AnomalyImage.Scale = new Vector2(1.5f, 1.5f);
    }
}